In [1]:
[1, 2, 1] #tek boyutlu liste

[1, 2, 1]

In [2]:
[[1, 2, 1], [3, 4, 3]] #çift boyutlu liste, matris gibi düşünülebilir ve bu matrisin 2 satırı ve 3 sütunu vardır yani 2x3'lük bir matristir.

[[1, 2, 1], [3, 4, 3]]

In [4]:
# ndarry: Numpy kütüphanesinin temel veri yapısıdır. Çok boyutlu dizileri (arrays) temsil eder ve
# bu diziler üzerinde hızlı ve verimli işlemler yapmayı sağlar.
#np.arange(): Belirtilen aralıkta düzenli aralıklarla sayılar oluşturan bir fonksiyondur.
#reshape(): Bir dizinin şeklini (shape) değiştirmek için kullanılır.

In [6]:
#Burada numpy kütüphanesini np olarak belirttik ve
#arange fonksiyonu ile 0'dan 14'e kadar olan sayıları oluşturduk ve
# reshape fonksiyonu ile bu sayıları 3 satır ve 5 sütunluk bir matrise dönüştürdük.
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.ndim #ndim: Dizinin kaç boyutlu olduğunu gösterir.

2

In [9]:
a.shape #Dizinin şekli (shape) yani satır ve sütun sayısını gösterir.

(3, 5)

In [10]:
a.dtype.name #Dizinin veri tipini gösterir.

'int64'

In [11]:
a.itemsize #Dizideki her bir elemanın byte cinsinden boyutunu gösterir.

8

In [12]:
a.size #Dizideki toplam eleman sayısını gösterir.

15

In [13]:
type(a)

numpy.ndarray

In [16]:
b = np.array([6, 7, 8]) #array: Numpy dizisi oluşturmak için kullanılır.
b

array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

In [18]:
#Ayrıca bir diziyi basit bir Python listesi ve demet yapmak için array fonksiyonunu kullanabiliriz.
a = np.array([2, 3 ,4])
a

array([2, 3, 4])

In [19]:
a.dtype

dtype('int64')

In [20]:
b = np.array([1.2, 3.5, 5.1]) #Bu sefer diziyi ondalık sayılarla oluşturduk.
b

array([1.2, 3.5, 5.1])

In [21]:
b.dtype

dtype('float64')

In [ ]:
#Burada dizi oluştururken birden fazla parametre kullanırsak hata alırız misal
a = np.array(1, 2, 3, 4) #TypeError: array() takes from 1 to 2 positional arguments but 4 were given hatası alırız.

In [30]:
b = np.array([(1.5, 2, 3),(4, 5, 6)])
# Diziler dizilerinin dizilerini iki boyutlu dizilere,
# dizilerinin dizilerinin dizilerini üç boyutlu dizilere ve benzeri şekillerde dönüştürür.
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [32]:
c = np.array([[1, 2], [3, 4]], dtype=complex) #Ayrıca istersek veri tpini değiştirebiliriz.
#Burada ise kompleks sayı olarak bir çift boyutlu dizi oluşturduk.
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
#Misal ben orijinal olarak dizimin elemanlarını bilmeyebilirim ama satır ve sütun sayısını biliyor olabilirim.
#Numpy bize birçok fonksiyon sunar bu fonksiyonlar ile istediğimiz şekillerde diziler oluşturabiliriz.
#Şu an zeros() ve ones() fonksiyonlarını göreceğiz.
#zeros(): Belirtilen şekle sahip ve tüm elemanları sıfır olan bir dizi oluşturur.
#ones(): Belirtilen şekle sahip ve tüm elemanları bir olan bir dizi oluşturur

In [ ]:
np.zeros((3,4))

In [ ]:
np.ones((2,3,4))

In [ ]:
#Bunlar default olarak float64 türünde diziler oluşturur. ama biz dtype parametresiyle istediğimiz veri tipini belirtebiliriz.

In [39]:
np.zeros((3,4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [40]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
#empty(): Belirtilen şekle sahip ve başlangıçta rastgele değerler içeren bir dizi oluşturur.
#Bu fonksiyonun oluşturduğu dizinin elemanları önceden bellekte bulunan rastgele değerlerdir.

In [45]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
#arange(): Belirtilen aralıkta düzenli aralıklarla sayılar oluşturan bir fonksiyondur.
np.arange(10, 30, 5) #10'dan 30'a kadar 5'er artan sayılar oluşturur.

array([10, 15, 20, 25])

In [47]:
np.arange(0, 2, 0.3) #0'dan 2'ye kadar 0.3'er artan sayılar oluşturur.

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [49]:
# ne zaman arange kayan noktalı argümanlarla kullanılırsa, elde edilen eleman sayısını tahmin etmek genellikle mümkün değildir, çünkü kayan nokta hassasiyeti sınırlıdır. Bu nedenle, adım yerine istediğimiz eleman sayısını argüman olarak alan linspace fonksiyonunu kullanmak genellikle daha iyidir:

In [50]:
from numpy import pi
np.linspace(0, 2, 9) #0'dan 2'ye kadar 9 eşit aralıklı sayı oluşturur.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [57]:
x = np.linspace(0, 2*pi, 100) #0'dan 2π'ye kadar 100 eşit aralıklı sayı oluşturur.
f = np.sin(x) #x dizisinin sinüs değerlerini hesaplar.
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [60]:
#Şimdi dizileri yazdıralım normalde numpy printleri yazdırırken iç içe listelerde gösterir yazdırırken şöyle okunur:
#-- İlk köşeli parantez dizinin başlangıcını gösterir.
#-- İkinci köşeli parantez ilk alt diziyi gösterir.
#-- Üçüncü köşeli parantez ise ikinci alt diziyi gösterir
a = np.arange(6) # 1 boyutlu dizi
print(a)

[0 1 2 3 4 5]


In [62]:
b = np.arange(12).reshape(4, 3) # 2 boyutlu dizi
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [64]:
c = np.arange(24).reshape(2, 3, 4) # 3 boyutlu dizi
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [65]:
#Ama bazen dizi büyük olduğunda numpy ortadaki elemanları atlar
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [66]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [67]:
import sys

#Bunu engellemek için numpy'nin print ayarlarını değiştirebiliriz.
np.set_printoptions(threshold=sys.maxsize)

In [69]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [70]:
#Şimdi ise bast operasyonlara bakalım
#Aritmetik işlemler eleman bazında yapılır.

In [75]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [76]:
c = a - b #Burada a dizisinden b dizisini çıkarttık. Sonrasında c dizisini yazdırdık.
c

array([20, 29, 38, 47])

In [77]:
b ** 2 #b dizisinin her bir elemanının karesini aldık.

array([0, 1, 4, 9])

In [80]:
10 * np.sin(a) #a dizisinin her bir elemanının sinüsünü alıp 10 ile çarptık.

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [81]:
a < 35 #a dizisinin her bir elemanının 35'ten küçük olup olmadığını kontrol ettik.

array([ True,  True, False, False])

In [83]:
#Bazı matriks işlemlerine ulaşmak içinse @ operatörünü kullanabiliriz.
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [84]:
A * B #Eleman bazında çarpma işlemi yapar.

array([[2, 0],
       [0, 4]])

In [85]:
A @ B #Matris çarpımı yapar.

array([[5, 4],
       [3, 4]])

In [86]:
A.dot(B) #Matris çarpımı yapar.

array([[5, 4],
       [3, 4]])

In [93]:
# += ve *= gibi operatörleri oluşturulmuş diziler üzerinde kullanabiliriz.
rg = np.random.default_rng() #Rastgele sayı üreteci oluşturur.
a = np.ones((2, 3), dtype=int) #2x3'lük bir dizi oluşturur ve tüm elemanları 1'dir.
b = rg.random((2, 3)) #2x3'lük bir dizi ve elemanları 0 ile 1 arasında rastgele sayılardır.


In [94]:
a *= 3 #a dizisinin her bir elemanını 3 ile çarpar.
print(a)

[[3 3 3]
 [3 3 3]]


In [95]:
b += a #b dizisinin her bir elemanına a dizisinin karşılık gelen elemanını ekler.
print(b)

[[3.41730313 3.12307266 3.98901083]
 [3.57940198 3.06638785 3.65525452]]


In [ ]:
a += b #Burada hata alırız çünkü a dizisi integer türünde ve b dizisi float türünde.
print(a)

In [ ]:
#Farklı veri tiplerinde olan diziler üzerinde işlemler yaparken dikkatli olmalıyız.
#Numpy otomatik olarak veri tiplerini dönüştürür ve bu bazen beklenmeyen sonuçlara yol açabilir.

In [97]:
a = np.ones(3, dtype=np.int32)#3 elemanlı bir dizi oluşturur ve tüm elemanları 1'dir.
b = np.linspace(0, pi, 3) #0'dan π'ye kadar 3 eşit aralıklı sayı oluşturur.

In [103]:
b.dtype.name

'float64'

In [104]:
c = a + b #a dizisi integer türünde ve b dizisi float türünde.
c

array([1.        , 2.57079633, 4.14159265])

In [105]:
c.dtype.name #Sonuç dizisi float türündedir çünkü numpy otomatik olarak veri tiplerini dönüştürür.

'float64'

In [106]:
d = np.exp(c * 1j) #c dizisinin her bir elemanını 1j ile çarpar ve exp fonksiyonunu uygular.
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [107]:
d.dtype.name

'complex128'

In [108]:
#ndarray'ler üzerinde matematiksel işlemler yaparken numpy'nin sunduğu fonksiyonları kullanabiliriz.
#Bu fonksiyonlar genellikle dizinin her bir elemanına uygulanır.


In [109]:
a = rg.random((2, 3)) #2x3'lük bir dizi ve elemanları 0 ile 1 arasında rastgele sayılardır.
a

array([[0.384398  , 0.9873931 , 0.4834878 ],
       [0.01305752, 0.62186956, 0.14799875]])

In [110]:
a.sum() #Dizinin tüm elemanlarının toplamını hesaplar.

np.float64(2.638204732460616)

In [111]:
a.min() #Dizinin en küçük elemanını bulur.

np.float64(0.013057521360174684)

In [112]:
a.max() #Dizinin en büyük elemanını bulur.

np.float64(0.9873931023534617)

In [121]:
#Eğer dizinin belirli bir ekseni boyunca işlemler yapmak istiyorsak axis parametresini kullanabiliriz.
#axis = 0 sütunlar boyunca işlemler yapar.
#axis = 1 satırlar boyunca işlemler yapar.
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
b.sum(axis= 0) #Sütunlar boyunca toplamı hesaplar.

array([12, 15, 18, 21])

In [123]:
b.min(axis = 1) #Satırlar boyunca en küçük elemanı bulur.

array([0, 4, 8])

In [124]:
b.cumsum(axis = 1) #Satırlar boyunca kümülatif toplamı hesaplar.

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [126]:
#Numpy bize benzer matematiksel fonksiyonlar sunar. Örneğin sin,cos,exp gibi bunlara biz universal functions (ufuncs) deriz.
B = np.arange(3)
B

array([0, 1, 2])

In [127]:
np.exp(B) #B dizisinin her bir elemanının üstelini alır. Yani e üzeri B[i]

array([1.        , 2.71828183, 7.3890561 ])

In [128]:
np.sqrt(B) #B dizisinin her bir elemanının karekökünü alır.

array([0.        , 1.        , 1.41421356])

In [129]:
C = np.array([2., -1., 4.])
np.add(B, C) #B ve C dizilerinin her bir elemanını toplar.

array([2., 0., 6.])

In [130]:
#Indeksleme, Dilimleme ve İterasyon
#Numpy dizileri üzerinde indeksleme ve dilimleme işlemleri yapabiliriz.
#Tek boyutlu dizilerde indeksleme ve dilimleme işlemleri Python listeleri ile aynıdır.
a = np.arange(10)**3 #0'dan 9'a kadar olan sayıların küplerini alır.
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [131]:
a[2]

np.int64(8)

In [132]:
a[2:5]

array([ 8, 27, 64])

In [134]:
a[:6:2] = 1000 #Dizinin ilk 6 elemanından her ikinci elemanı 1000 yapar.
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [135]:
a[::-1] #Diziyi tersten yazdırır.

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [136]:
for i in a: #Dizinin her bir elemanını yazdırır.
    print(i**(1/3.)) #Küp kökünü alır.

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [138]:
#Çok boyutlu dizilerde ise indeksleme ve dilimleme işlemleri biraz daha karmaşıktır. Burada her bir eksen için ayrı ayrı indeksleme yapabiliriz.
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f,(5, 4),dtype=int) #5x4'lük bir dizi oluşturur ve her bir elemanı f fonksiyonu ile belirler.
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [139]:
b[2, 3] #2. satır ve 3. sütundaki elemanı alır.

np.int64(23)

In [140]:
b[0:5, 1] #Tüm satırlardan 1. sütunu alır.

array([ 1, 11, 21, 31, 41])

In [142]:
b[:,1] #Tüm satırlardan 1. sütunu alır.

array([ 1, 11, 21, 31, 41])

In [143]:
b[1:3, :] #1. ve 2. satırları alır.

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [144]:
b[-1] #Son satırı alır.

array([40, 41, 42, 43])

In [146]:
# ... operatörü ile eksenleri atlayabiliriz.
#Bu dizide 3 boyutlu bir dizi oluşturalım.
c = np.array([[[0, 1, 2],
               [10, 12, 13]],

              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [147]:
c[1, ...] #1. bloktaki tüm satır ve sütunları alır. c[1,:,:] ile aynı işlemi yapar.

array([[100, 101, 102],
       [110, 112, 113]])

In [148]:
c[..., 2] #Tüm bloklardan 2. sütunu alır. c[:,:,2] ile aynı işlemi yapar.

array([[  2,  13],
       [102, 113]])

In [153]:
#Yani özetlersek ilk indeks blokları, ikinci indeks satırları ve üçüncü indeks sütunları temsil eder.

In [154]:
#İterasyonlar da ise çok boyutlu dizilerde ilk eksen boyunca iterasyon yapılır.
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [156]:
#Ama bazen tüm elemanlar üzerinde iterasyon yapmak isteyebiliriz.
for element in b.flat: #flat özelliği diziyi tek boyutlu hale getirir ve tüm elemanlar üzerinde iterasyon yapmayı sağlar.
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
