In [8]:
import numpy as np
rg = np.random.default_rng() #Rastgele sayı üreteci oluşturur.
a = np.floor(10 * rg.random((3, 4))) #2x3'lük bir dizi ve elemanları 0 ile 10 arasında rastgele tam sayılardır.
print(a.shape)
#Floor fonksiyonu ondalıklı sayıları en yakın alt tam sayıya yuvarlar.

(3, 4)


In [13]:
print(a)

[[1. 4. 2. 8.]
 [9. 9. 7. 2.]
 [2. 6. 3. 4.]]


In [9]:
a.ravel() #Diziyi tek boyuta indirger. Bunu yaparken a[0,0], a[0,1], a[0,2], a[0,3], a[1,0] ... şeklinde ilerler.

array([1., 4., 2., 8., 9., 9., 7., 2., 2., 6., 3., 4.])

In [10]:
a.reshape(6, 2) #Diziyi 6x2 boyutuna getirir. Burada da aynı şekilde elemanları satır bazında alır.

array([[1., 4.],
       [2., 8.],
       [9., 9.],
       [7., 2.],
       [2., 6.],
       [3., 4.]])

In [11]:
a.T #Dizinin transpozunu alır. Transpoz, satır ve sütunların yer değiştirmesidir.

array([[1., 9., 2.],
       [4., 9., 6.],
       [2., 7., 3.],
       [8., 2., 4.]])

In [12]:
a.T.shape #Peki 6x2 boyutundan 4x3 boyutuna nasıl döndük?
#Burada şöyle olmuştur: a dizisi 3 satır ve 4 sütundan oluşuyordu. Transpoz işlemi ile satırlar sütun, sütunlar ise satır oldu.

(4, 3)

In [14]:
a.shape

(3, 4)

In [15]:
#ama ben resize ile yaparsam bu sefer a dizisi kalıcı olarak değişir.
a

array([[1., 4., 2., 8.],
       [9., 9., 7., 2.],
       [2., 6., 3., 4.]])

In [17]:
a.resize(2,6) #Diziyi 2x6 boyutuna getirir ve a dizisini kalıcı olarak değiştirir.
a

array([[1., 4., 2., 8., 9., 9.],
       [7., 2., 2., 6., 3., 4.]])

In [20]:
#Eğer ben boyutu -1 yaparsam numpy otomatik olarak diğer boyutu hesaplar.
a.resize(3,4) #Önce a dizisini eski haline getiriyorum
a.reshape(3, -1) #Burada 4'ü numpy otomatik olarak hesaplar.

array([[1., 4., 2., 8.],
       [9., 9., 7., 2.],
       [2., 6., 3., 4.]])

In [21]:
#Birçok diziyi yığınlayabiliriz.
a = np.floor(10 * rg.random((2, 2))) #2x2'lik bir dizi oluşturur.
b = np.floor(10 * rg.random((2, 2))) #2x2'lik bir dizi oluşturur.


In [23]:
print(a)
print(b)

[[3. 7.]
 [4. 6.]]
[[0. 3.]
 [1. 5.]]


In [24]:
np.vstack((a, b)) #a ve b dizilerini dikey olarak yığınlar. Sonuç 4x2 boyutunda olur.

array([[3., 7.],
       [4., 6.],
       [0., 3.],
       [1., 5.]])

In [25]:
np.hstack((a, b)) #a ve b dizilerini yatay olarak yığınlar. Sonuç 2x4 boyutunda olur.

array([[3., 7., 0., 3.],
       [4., 6., 1., 5.]])

In [26]:
#Ayrıca column_stack ile de 1 boyutlu dizileri 2 boyutlu yapabiliriz.
from numpy import newaxis #newaxis, dizilere yeni bir eksen eklemek için kullanılır.
np.column_stack((a, b))

array([[3., 7., 0., 3.],
       [4., 6., 1., 5.]])

In [80]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [28]:
np.hstack((a, b)) #hstack ile yaparsak 1 boyutlu kalır.

array([4., 2., 3., 8.])

In [30]:
a[:, newaxis] #a dizisine yeni bir eksen ekler ve 2 boyutlu yapar.

array([[4.],
       [2.]])

In [31]:
b[:, newaxis] #b dizisine yeni bir eksen ekler ve 2 boyutlu yapar.

array([[3.],
       [8.]])

In [34]:
np.column_stack((a[:, newaxis], b[:, newaxis])) #newaxis ile eklenen eksenler sayesinde column_stack ile yığınlayabiliriz.)

array([[4., 3.],
       [2., 8.]])

In [35]:
np.hstack((a[:, newaxis], b[:, newaxis])) #hstack ile de yığınlayabiliriz.

array([[4., 3.],
       [2., 8.]])

In [36]:
#Genel olarak eğer birden fazla boyutlu diziler varsa:
#hstacks ikinci eksen boyunca yığınlama yapar.
#vstacks birinci eksen boyunca yığınlama yapar.
#concatenate ise belirtilen eksen boyunca yığınlama yapar.

In [82]:
np.concatenate((a, b), axis=0) #axis=0 birinci eksen boyunca yığınlama yapar.

array([4., 2., 3., 8.])

In [47]:
#Kompleks dizilerde ise r_ ve c_ kullanabiliriz. Bunlar sırasıyla row ve column anlamına gelir. : kullanımına izin verir
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [50]:
np.c_[(1,0,4),(1,2,3)]

array([[1, 1],
       [0, 2],
       [4, 3]])

In [56]:
#Bir diziyi parçalara ayırabiliriz bunu split fonksiyonu ile yaparız.
#hsplit şöyle bölümleme yapar: yatay olarak böler yani sütunlardan böler.
a = np.floor(10 * rg.random((2,12))) #2x12'lik bir dizi oluşturur.
a

array([[4., 8., 1., 3., 7., 5., 7., 0., 1., 5., 6., 4.],
       [5., 6., 4., 1., 4., 1., 8., 1., 5., 3., 4., 1.]])

In [57]:
#Split ile a'yı 3 parçaya bölelim.
np.hsplit(a, 3) #Burada 3 parçaya böldük.

[array([[4., 8., 1., 3.],
        [5., 6., 4., 1.]]),
 array([[7., 5., 7., 0.],
        [4., 1., 8., 1.]]),
 array([[1., 5., 6., 4.],
        [5., 3., 4., 1.]])]

In [63]:
#Split ile a'yı 3. ve 4. sütunlardan bölelim.
np.hsplit(a, (3,5)) #Burada belirtilen sütun sayısını hangi sütuna kadar böleceğimizi belirtiyoruz.
#Yani 0-2, 3-4, 5-11 şeklinde 3 parça olur.

[array([[4., 8., 1.],
        [5., 6., 4.]]),
 array([[3., 7.],
        [1., 4.]]),
 array([[5., 7., 0., 1., 5., 6., 4.],
        [1., 8., 1., 5., 3., 4., 1.]])]

In [66]:
np.vsplit(a,2) #vsplit ile a'yı 2 parçaya böleriz. Burada satırlardan böler. Burada dikkat etmen gereken ne kadar satır varsa o kadar parçaya bölebilirsin. Yoksa hata verir.

[array([[4., 8., 1., 3., 7., 5., 7., 0., 1., 5., 6., 4.]]),
 array([[5., 6., 4., 1., 4., 1., 8., 1., 5., 3., 4., 1.]])]

In [68]:
b = np.floor(10 * rg.random((12,6))) #12x2'lik bir dizi oluşturur.
b

array([[6., 2., 0., 5., 4., 9.],
       [7., 5., 8., 2., 8., 7.],
       [2., 2., 8., 9., 6., 5.],
       [8., 0., 0., 3., 6., 6.],
       [6., 2., 8., 5., 4., 1.],
       [0., 0., 2., 9., 8., 7.],
       [1., 3., 6., 4., 0., 9.],
       [2., 1., 1., 4., 6., 6.],
       [8., 0., 8., 3., 5., 0.],
       [0., 7., 6., 0., 0., 5.],
       [3., 7., 9., 9., 6., 2.],
       [0., 9., 1., 5., 7., 6.]])

In [70]:
np.vsplit(b, 3) #b dizisini 4 parçaya böler. Her parça 3 satır olur.

[array([[6., 2., 0., 5., 4., 9.],
        [7., 5., 8., 2., 8., 7.],
        [2., 2., 8., 9., 6., 5.],
        [8., 0., 0., 3., 6., 6.]]),
 array([[6., 2., 8., 5., 4., 1.],
        [0., 0., 2., 9., 8., 7.],
        [1., 3., 6., 4., 0., 9.],
        [2., 1., 1., 4., 6., 6.]]),
 array([[8., 0., 8., 3., 5., 0.],
        [0., 7., 6., 0., 0., 5.],
        [3., 7., 9., 9., 6., 2.],
        [0., 9., 1., 5., 7., 6.]])]

In [71]:
np.vsplit(b,(3,4)) #b dizisini 3. ve 4. satırlardan böler. Yani 0-2, 3, 4-11 şeklinde 3 parça olur.

[array([[6., 2., 0., 5., 4., 9.],
        [7., 5., 8., 2., 8., 7.],
        [2., 2., 8., 9., 6., 5.]]),
 array([[8., 0., 0., 3., 6., 6.]]),
 array([[6., 2., 8., 5., 4., 1.],
        [0., 0., 2., 9., 8., 7.],
        [1., 3., 6., 4., 0., 9.],
        [2., 1., 1., 4., 6., 6.],
        [8., 0., 8., 3., 5., 0.],
        [0., 7., 6., 0., 0., 5.],
        [3., 7., 9., 9., 6., 2.],
        [0., 9., 1., 5., 7., 6.]])]

In [77]:
#array_split ile de bölebiliriz. array_split ile bölersek eşit olmayan parçalara da bölebiliriz.
np.array_split(b, 3, axis=1) #a dizisini 3 parçaya böler. axis=1 sütunlardan böler.

[array([[6., 2.],
        [7., 5.],
        [2., 2.],
        [8., 0.],
        [6., 2.],
        [0., 0.],
        [1., 3.],
        [2., 1.],
        [8., 0.],
        [0., 7.],
        [3., 7.],
        [0., 9.]]),
 array([[0., 5.],
        [8., 2.],
        [8., 9.],
        [0., 3.],
        [8., 5.],
        [2., 9.],
        [6., 4.],
        [1., 4.],
        [8., 3.],
        [6., 0.],
        [9., 9.],
        [1., 5.]]),
 array([[4., 9.],
        [8., 7.],
        [6., 5.],
        [6., 6.],
        [4., 1.],
        [8., 7.],
        [0., 9.],
        [6., 6.],
        [5., 0.],
        [0., 5.],
        [6., 2.],
        [7., 6.]])]

In [88]:
#Şimdi kopyalama ve görünüm oluşturmayı görelim.
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])

In [90]:
b = a #b dizisi a dizisine referans olur. Yani b'de yapılan değişiklikler a'yı da etkiler. Yeni obje oluşturulmaz.

In [91]:
b is a #b ve a aynı nesneyi mi gösteriyor sorusunu cevaplar.

True

In [92]:
def f(x):
    print(id(x)) #x'in bellek adresini yazdırır.
id(a) #a'nın bellek adresini yazdırır.

4491957648

In [93]:
f(a) #belirttiğimiz fonksiyona a dizisini gönderiyoruz. Yeni obje oluşturulmaz.

4491957648


In [96]:
#Gösterme (View) ve Yüzeysel Kopya (Shallow Copy)
c = a.view() #b dizisi a dizisinin bir görünümüdür. Yeni obje oluşturulur ama veri paylaşılır.
c is a

False

In [97]:
c.base is a #c dizisi a dizisinden oluşturulduğu için a dizisine referans olur.

True

In [99]:
c.flags.owndata #c dizisi kendi verisine sahip değil.

False

In [100]:
c = c.reshape(2, 6) #c dizisinin şeklini değiştiriyoruz.

In [101]:
a.shape #a dizisinin şekli değişmedi.

(3, 4)

In [103]:
c[0, 4] = 1234 #c dizisinin bir elemanını değiştiriyoruz.
a #burada a dizisi de etkilendi çünkü veri paylaşılıyor.

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [104]:
s = a[:,1:3] #a dizisinin bir parçasını alıyoruz.
s[:] = 10 #s dizisinin tüm elemanlarını 10 yapıyoruz.
a #a dizisi de etkilendi çünkü veri paylaşılıyor.

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [105]:
#Kısaca şöyle diyelim verilerle oynarsak orijinal dizi de etkilenir. Ama şekil ile oynarsak orijinal dizi etkilenmez.

In [106]:
#Deep copy (Derin Kopya)
d = a.copy() #a dizisinin derin kopyasını oluşturur. Yeni obje oluşturulur ve veri paylaşılmaz.
d is a

False

In [107]:
d.base is a #d dizisi a dizisinden oluşturulmadığı için a dizisine referans olmaz.

False

In [109]:
d[0, 0] = 9999 #d dizisinin bir elemanını değiştiriyoruz.
a #a dizisi etkilenmez çünkü veri paylaşılmıyor.

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [110]:
#Bazen copy dilimlemeden sonra çağırılır çğnkü orijinal diziye gerek kalmaz örneğin a büyük bir sonuç döndüyse ve biz sadece a'nın bir parçasını ile çalışacaksak bunu b'ye atamak istiyorsak copy kullanmak mantıklıdır.
a = np.arange(int(1e8)) #1e8 yani 100 milyon elemanlı bir dizi oluşturur.
b = a[:100].copy() #a dizisinin ilk 100 elemanını alıyoruz ve derin kopyasını oluşturuyoruz.
del a #a dizisini siliyoruz.

In [111]:
#eğer bunun yerine b = a[:100] yapsaydık b dizisi a dizisine referans olurdu ve a dizisi silindiğinde b dizisi de geçersiz olurdu.

In [113]:
#Broadcasting
#Broadcasting, farklı şekillere sahip dizilerle yapılan işlemlerde kullanılır.
#Numpy, daha küçük diziyi otomatik olarak genişleterek aynı şekle getirir ve ardından eleman bazında işlemi gerçekleştirir.
#İki kural vardır:
#Girdiler eğer aynı şekle sahip değilse "1" ile küçük olan eksenler genişletilir.
#Ve o birlerin boyutu diğer dizinin boyutuna eşitlenir. Sonrasında yayın dizisi için o boyut işlemi yapılır
#Bunun sonucunda her iki dizi de aynı şekle sahip olur ve eleman bazında işlem yapılabilir.